// src/react/flowchart-builder/ts/src/action-component.tsx
import React from 'react'

/**
 * Component used to render an action node.
 */
export default function ActionComponent({ctx, nodeOps}) {

    const { vertex, surface, toolkit } = ctx;
    const data = vertex.data;

    return <div style={{width:data.w + 'px', height:data.h + 'px'}} className="flowchart-object flowchart-action" data-jtk-target="true" data-jtk-port-type="target">
        <svg width={data.w} height={data.h}>
            <rect x={10} y={10} width={data.w-20} height={data.h-20} className="inner" rx={5} ry={5}/>
        </svg>
        <span>{data.text}</span>
        <div className="node-edit node-action" onClick={() => nodeOps.edit(vertex, toolkit)}></div>
        <div className="node-delete node-action" onClick={() => nodeOps.remove(vertex, toolkit)}></div>
        <div className="drag-start connect" data-jtk-source="true" data-jtk-port-type="source"></div>
    </div>
}

// src/svelte/flowchart-builder/components/ActionComponent.svelte
<script>

    export let data;
    export let toolkit;
    export let surface;
    export let vertex;

    export let manager

</script>

<div style="width:{data.w}px;height:{data.h}px" class="flowchart-object flowchart-action" data-jtk-target="true" data-jtk-port-type="target">
    <svg width={data.w} height={data.h}>
        <rect x="10" y="10" width={data.w-20} height={data.h-20} class="inner" rx="5" ry="5"/>
    </svg>
    <span>{data.text}</span>
    <div class="node-edit node-action" on:click={() => manager.edit(vertex)}></div>
    <div class="node-delete node-action" on:click={() => manager.remove(vertex)}></div>
    <div class="drag-start connect" data-jtk-source="true" data-jtk-port-type="source"></div>
</div>
