// src/react/flowchart-builder/ts/src/output-component.tsx
import * as React from 'react'


/**
 * Component used to render an output node.
 */
export default function OutputComponent ({ctx, nodeOps}) {

    const { vertex, surface, toolkit } = ctx;
    const data = vertex.data;

    return <div style={{width:data.w + 'px', height:data.h + 'px'}} className="flowchart-object flowchart-output" data-jtk-target="true" data-jtk-port-type="target">
        <svg width={data.w} height={data.h}>
            <rect x={0} y={0} width={data.w} height={data.h} rx={5} ry={5}/>
        </svg>
        <span>{data.text}</span>
        <div className="node-edit node-action" onClick={() => nodeOps.edit(vertex, toolkit)}></div>
        <div className="node-delete node-action" onClick={() => nodeOps.remove(vertex, toolkit)}></div>
    </div>
}

// src/svelte/flowchart-builder/components/OutputComponent.svelte
<script>

    export let data;
    export let toolkit;
    export let surface;
    export let vertex;

    export let manager
</script>


<div style="width:{data.w}px;height:{data.h}px" class="flowchart-object flowchart-output" data-jtk-target="true" data-jtk-port-type="target">
    <svg width={data.w} height={data.h}>
        <rect x={0} y={0} width={data.w} height={data.h} rx={5} ry={5}/>
    </svg>
    <span>{data.text}</span>
    <div class="node-edit node-action" on:click={() => manager.edit(vertex)}></div>
    <div class="node-delete node-action" on:click={() => manager.remove(vertex)}></div>
</div>
