// src/angular/flowchart-builder/src/controls.ts
import {AfterViewInit, Component, ElementRef, Input} from '@angular/core'

import {
  EVENT_UNDOREDO_UPDATE,
  UndoRedoUpdateParams,
  EVENT_CANVAS_CLICK,
  EVENT_SURFACE_MODE_CHANGED,
  Surface,
  SurfaceMode,
  FALSE, TRUE
} from '@jsplumbtoolkit/browser-ui'
import {jsPlumbService} from '@jsplumbtoolkit/browser-ui-angular'

// --------------------------------------- CONTROLS COMPONENT ------------------------------------------------------------------
//
// This component was written for the jsPlumb Toolkit demonstrations. It's production ready of course, but it assumes a couple of
// other styles are available (via jsplumbtoolkit-demo-support.css), and it has
// hardcoded labels in English.


@Component({
  selector: 'jsplumb-controls',
  template: `<div class="controls">
              <i class="fa fa-arrows selected-mode" mode="pan" title="Pan Mode" (click)="panMode()"></i>
              <i class="fa fa-pencil" mode="select" title="Select Mode" (click)="selectMode()"></i>
              <i class="fa fa-home" reset title="Zoom To Fit" (click)="zoomToFit()"></i>
              <i class="fa fa-undo" undo title="Undo last action" (click)="undo()"></i>
              <i class="fa fa-repeat" redo title="Redo last action" (click)="redo()"></i>
              <i class="fa fa-times" title="Clear flowchart" (click)="clear()"></i>
          </div>`
})
export class ControlsComponent implements AfterViewInit {

  @Input() surfaceId: string

  surface: Surface

  constructor(private el: ElementRef, private $jsplumb: jsPlumbService) { }

  getNativeElement(component: any) {
    return (component.nativeElement || component._nativeElement || component.location.nativeElement).childNodes[0]
  }

  panMode() {
    this.surface.setMode(SurfaceMode.PAN)
  }

  selectMode() {
    this.surface.setMode(SurfaceMode.SELECT)
  }

  zoomToFit() {
    this.surface.toolkitInstance.clearSelection()
    this.surface.zoomToFit()
  }

  undo() {
    this.surface.toolkitInstance.undo()
  }

  redo() {
    this.surface.toolkitInstance.redo()
  }

  ngAfterViewInit() {
    this.$jsplumb.getSurface(this.surfaceId, (s: Surface) => {

      this.surface = s
      this.surface.bind(EVENT_SURFACE_MODE_CHANGED, (mode: string) => {
        const controls = this.getNativeElement(this.el)
        this.surface.removeClass(controls.querySelectorAll('[mode]'), 'selected-mode')
        this.surface.addClass(controls.querySelectorAll(`[mode='${mode}']`), 'selected-mode')
      });

      this.surface.toolkitInstance.bind(EVENT_UNDOREDO_UPDATE, (state: UndoRedoUpdateParams) => {
        const controls = this.getNativeElement(this.el)
        controls.setAttribute('can-undo', state.undoCount > 0 ? TRUE : FALSE)
        controls.setAttribute('can-redo', state.redoCount > 0 ? TRUE : FALSE)
      })

      this.surface.bind(EVENT_CANVAS_CLICK, () => this.surface.toolkitInstance.clearSelection())

    })
  }

  clear() {
    const t = this.surface.toolkitInstance
    if (t.getNodeCount() === 0 || confirm('Clear flowchart?')) {
      t.clear()
    }
  }
}


// -------------------------------------------- / CONTROLS COMPONENT ----------------------------------------------------

// src/react/database-visualizer/es6/src/controls-component.jsx
import React from 'react';

import { EVENT_UNDOREDO_UPDATE } from "@jsplumbtoolkit/browser-ui"

export class ControlsComponent extends React.Component {

    constructor(props) {
        super(props)
    }

    render() {
        return <div className="controls" ref={(c) => this._container = c}>
            <i className="fa fa-arrows selected-mode" data-mode="pan" title="Pan Mode" onClick={this.panMode.bind(this)}/>
            <i className="fa fa-pencil" data-mode="select" title="Select Mode" onClick={this.selectMode.bind(this)}/>
            <i className="fa fa-home" data-reset title="Zoom To Fit" onClick={this.reset.bind(this)}/>
            <i className="fa fa-undo" undo="true" title="Undo last action" onClick={this.undo.bind(this)}/>
            <i className="fa fa-repeat" redo="true" title="Redo last action" onClick={this.redo.bind(this)}/>
        </div>
    }

    initialize(surface) {
        this.surface = surface;
        this.toolkit = surface.toolkitInstance
        this.toolkit.bind(EVENT_UNDOREDO_UPDATE, (state) => {
            this._container.setAttribute("can-undo", state.undoCount > 0 ? "true" : "false")
            this._container.setAttribute("can-redo", state.redoCount > 0 ? "true" : "false")
        })

        this.surface.bind("modeChanged", (mode) => {
            // jsPlumb.removeClass(this._container.querySelectorAll("[data-mode]"), "selected-mode");
            // jsPlumb.addClass(this._container.querySelectorAll("[data-mode='" + mode + "']"), "selected-mode");
        });

        this.surface.bind("canvasClick", (e) => {
            this.toolkit.clearSelection();
        });
    }

    reset() {
        this.toolkit.clearSelection();
        this.surface.zoomToFit();
    }

    panMode() {
        this.surface.setMode("pan");
    }

    selectMode() {
        this.surface.setMode("select");
    }

    undo() {
        this.toolkit.undo()
    }

    redo() {
        this.toolkit.redo()
    }
}
